[[songs]]
id = 2
artist = "Pyrokinesis"
name = "Море волнуется два (припев)"
song_cover_path = "pyrokinesis__seegrowthtwo.jpg"
preview_tabs_path = "pyrokinesis__seegrowthtwo.jpg"
demo_sound_path = "pyrokinesis__seegrowthtwo.wav"
demo_sound_duration = 38
buy_in_usd_link = "https://boosty.to/deknowny/posts/d5e09178-8480-4202-85b8-a53024e8469c"
price = 99



[[songs]]
id = 3
artist = "Ooes"
name = "Ночь (припев)"
song_cover_path = "ooes__night.jpg"
preview_tabs_path = "ooes__night.png"
demo_sound_path = "ooes__night.flac"
demo_sound_duration = 28
buy_in_usd_link = "https://boosty.to/deknowny/posts/2348826f-ea33-46d5-ae43-e1714459f166"
price = 99
